# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ProgramUpdate(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, nombre: str=None, descripcion: str=None, estado: int=None):  # noqa: E501
        """ProgramUpdate - a model defined in Swagger

        :param nombre: The nombre of this ProgramUpdate.  # noqa: E501
        :type nombre: str
        :param descripcion: The descripcion of this ProgramUpdate.  # noqa: E501
        :type descripcion: str
        :param estado: The estado of this ProgramUpdate.  # noqa: E501
        :type estado: int
        """
        self.swagger_types = {
            'nombre': str,
            'descripcion': str,
            'estado': int
        }

        self.attribute_map = {
            'nombre': 'nombre',
            'descripcion': 'descripcion',
            'estado': 'estado'
        }
        self._nombre = nombre
        self._descripcion = descripcion
        self._estado = estado

    @classmethod
    def from_dict(cls, dikt) -> 'ProgramUpdate':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ProgramUpdate of this ProgramUpdate.  # noqa: E501
        :rtype: ProgramUpdate
        """
        return util.deserialize_model(dikt, cls)

    @property
    def nombre(self) -> str:
        """Gets the nombre of this ProgramUpdate.


        :return: The nombre of this ProgramUpdate.
        :rtype: str
        """
        return self._nombre

    @nombre.setter
    def nombre(self, nombre: str):
        """Sets the nombre of this ProgramUpdate.


        :param nombre: The nombre of this ProgramUpdate.
        :type nombre: str
        """

        self._nombre = nombre

    @property
    def descripcion(self) -> str:
        """Gets the descripcion of this ProgramUpdate.


        :return: The descripcion of this ProgramUpdate.
        :rtype: str
        """
        return self._descripcion

    @descripcion.setter
    def descripcion(self, descripcion: str):
        """Sets the descripcion of this ProgramUpdate.


        :param descripcion: The descripcion of this ProgramUpdate.
        :type descripcion: str
        """

        self._descripcion = descripcion

    @property
    def estado(self) -> int:
        """Gets the estado of this ProgramUpdate.


        :return: The estado of this ProgramUpdate.
        :rtype: int
        """
        return self._estado

    @estado.setter
    def estado(self, estado: int):
        """Sets the estado of this ProgramUpdate.


        :param estado: The estado of this ProgramUpdate.
        :type estado: int
        """

        self._estado = estado
