# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Program(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: int=None, nombre: str=None, descripcion: str=None, estado: int=None):  # noqa: E501
        """Program - a model defined in Swagger

        :param id: The id of this Program.  # noqa: E501
        :type id: int
        :param nombre: The nombre of this Program.  # noqa: E501
        :type nombre: str
        :param descripcion: The descripcion of this Program.  # noqa: E501
        :type descripcion: str
        :param estado: The estado of this Program.  # noqa: E501
        :type estado: int
        """
        self.swagger_types = {
            'id': int,
            'nombre': str,
            'descripcion': str,
            'estado': int
        }

        self.attribute_map = {
            'id': 'id',
            'nombre': 'nombre',
            'descripcion': 'descripcion',
            'estado': 'estado'
        }
        self._id = id
        self._nombre = nombre
        self._descripcion = descripcion
        self._estado = estado

    @classmethod
    def from_dict(cls, dikt) -> 'Program':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Program of this Program.  # noqa: E501
        :rtype: Program
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this Program.


        :return: The id of this Program.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this Program.


        :param id: The id of this Program.
        :type id: int
        """

        self._id = id

    @property
    def nombre(self) -> str:
        """Gets the nombre of this Program.


        :return: The nombre of this Program.
        :rtype: str
        """
        return self._nombre

    @nombre.setter
    def nombre(self, nombre: str):
        """Sets the nombre of this Program.


        :param nombre: The nombre of this Program.
        :type nombre: str
        """

        self._nombre = nombre

    @property
    def descripcion(self) -> str:
        """Gets the descripcion of this Program.


        :return: The descripcion of this Program.
        :rtype: str
        """
        return self._descripcion

    @descripcion.setter
    def descripcion(self, descripcion: str):
        """Sets the descripcion of this Program.


        :param descripcion: The descripcion of this Program.
        :type descripcion: str
        """

        self._descripcion = descripcion

    @property
    def estado(self) -> int:
        """Gets the estado of this Program.


        :return: The estado of this Program.
        :rtype: int
        """
        return self._estado

    @estado.setter
    def estado(self, estado: int):
        """Sets the estado of this Program.


        :param estado: The estado of this Program.
        :type estado: int
        """

        self._estado = estado
